### ISSUE TITLE
The Goblin mod causes the game to crash due to entity ID conflicts with other mods

### ISSUE THREAD

**Issue by Omgise** [Rozmir-Rohi/goblins-legacy#2]
I hope that the entity IDs of these goblins can be changed in the configuration file, so that there will be no conflicts.
[crash-2024-12-15_08.11.08-client.txt](https://github.com/user-attachments/files/18138267/crash-2024-12-15_08.11.08-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/18138268/fml-client-latest.log)

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit.
Goblins Legacy will now try to find a unique starting mod entity ID by default.
Also added a config option to override the default automatic starting ID with a custom starting mod entity ID.
